require('dotenv').config();

const fs = require('fs');
const path = require('path');
const http = require('http');
const express = require('express');
const cors = require('cors');
const WebSocket = require('ws');
const { createClient, LiveTranscriptionEvents } = require('@deepgram/sdk');

const PORT = Number(process.env.PORT || 8080);
const DEEPGRAM_API_KEY = process.env.DEEPGRAM_API_KEY;
const DG_MODEL = process.env.DG_MODEL || 'nova-3';
const DG_LANGUAGE = process.env.DG_LANGUAGE || 'en-US';
const DG_ENDPOINTING_MS = Number(process.env.DG_ENDPOINTING_MS || 60);
const DG_UTTERANCE_END_MS = Number(process.env.DG_UTTERANCE_END_MS || 700);
const USERS_FILE = path.join(__dirname, 'users.json');

if (!DEEPGRAM_API_KEY) {
  console.warn('[Backend] WARNING: DEEPGRAM_API_KEY missing. STT will not work until configured.');
}

function loadUsers() {
  try { return JSON.parse(fs.readFileSync(USERS_FILE, 'utf8')); }
  catch { return {}; }
}

function validateLicense(email, licenseKey) {
  const users = loadUsers();
  const cleanEmail = String(email || '').trim().toLowerCase();
  const cleanKey = String(licenseKey || '').trim();
  const user = users[cleanEmail];
  if (!user) return { ok: false, reason: 'License email not found' };
  if (!user.active) return { ok: false, reason: 'License inactive' };
  if (user.licenseKey !== cleanKey) return { ok: false, reason: 'Invalid license key' };
  const today = new Date().toISOString().slice(0, 10);
  if (user.validTill < today) return { ok: false, reason: `License expired on ${user.validTill}` };
  return { ok: true, user };
}

const app = express();
app.use(cors());
app.use(express.json({ limit: '1mb' }));

app.get('/health', (_, res) => res.json({ ok: true, service: 'meeting-caption-backend' }));

app.post('/api/license/check', (req, res) => {
  const result = validateLicense(req.body.email, req.body.licenseKey);
  res.status(result.ok ? 200 : 403).json(result.ok ? {
    ok: true,
    validTill: result.user.validTill,
    plan: result.user.plan
  } : { ok: false, error: result.reason });
});

// First 10-20 users: Razorpay can be handled manually using payment links.
// Later you can connect webhooks here and auto-create/extend users.json.
app.post('/api/razorpay/webhook', (req, res) => {
  console.log('[RazorpayWebhook] Received event:', req.body?.event || 'unknown');
  res.json({ ok: true, message: 'Webhook received. Manual license update is enabled in v16.' });
});

const server = http.createServer(app);
const wss = new WebSocket.Server({ server, path: '/stt' });

wss.on('connection', (client, req) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const email = url.searchParams.get('email');
  const licenseKey = url.searchParams.get('licenseKey');
  const license = validateLicense(email, licenseKey);

  if (!license.ok) {
    const reason = license.reason + '. Open License in the overlay and activate with the same email/license generated by backend.';
    client.send(JSON.stringify({ type: 'error', message: reason }));
    client.close(4001, reason);
    return;
  }

  if (!DEEPGRAM_API_KEY) {
    client.send(JSON.stringify({ type: 'error', message: 'Backend Deepgram key is not configured' }));
    client.close(4002, 'Deepgram key missing');
    return;
  }

  console.log(`[STT] Client connected: ${email}`);
  client.send(JSON.stringify({ type: 'status', text: 'License valid. Starting low-latency transcription...' }));

  const deepgram = createClient(DEEPGRAM_API_KEY);
  const dg = deepgram.listen.live({
    // Accuracy: nova-3 gives better conversational accuracy than nova-2 when available on the account.
    model: DG_MODEL,
    language: DG_LANGUAGE,
    encoding: 'linear16',
    sample_rate: 16000,
    channels: 1,

    // Latency: stream interim words immediately; do not wait for final sentence closure.
    interim_results: true,
    vad_events: true,
    endpointing: DG_ENDPOINTING_MS,
    utterance_end_ms: DG_UTTERANCE_END_MS,

    // Readability: keep final captions formatted without blocking interim captions.
    punctuate: true,
    smart_format: true,
  });

  let dgReady = false;
  let audioBuffer = [];
  const keepAlive = setInterval(() => {
    try { dg?.keepAlive?.(); } catch (_) {}
  }, 8000);

  dg.on(LiveTranscriptionEvents.Open, () => {
    dgReady = true;
    client.send(JSON.stringify({ type: 'status', text: `Deepgram connected (${DG_MODEL}). Low-latency captions active...` }));
    for (const chunk of audioBuffer.splice(0)) {
      try { dg.send(chunk); } catch (_) {}
    }
  });

  dg.on(LiveTranscriptionEvents.Transcript, (data) => {
    const alt = data?.channel?.alternatives?.[0];
    const text = (alt?.transcript || '').trim();
    if (!text) return;
    client.send(JSON.stringify({
      type: 'transcript',
      text,
      isFinal: !!data?.is_final,
      confidence: alt?.confidence || 0
    }));
  });

  dg.on(LiveTranscriptionEvents.SpeechStarted, () => {
    client.send(JSON.stringify({ type: 'speech_started' }));
  });

  dg.on(LiveTranscriptionEvents.Error, (err) => {
    const message = err?.message || String(err);
    console.error('[Deepgram] Error:', message);
    client.send(JSON.stringify({ type: 'error', message }));
  });

  dg.on(LiveTranscriptionEvents.Close, () => {
    dgReady = false;
    clearInterval(keepAlive);
  });

  client.on('message', (chunk) => {
    const buf = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
    if (dgReady) {
      try { dg.send(buf); } catch (e) { console.error('[STT] send error:', e.message); }
    } else {
      audioBuffer.push(buf);
      // Keep only a tiny pre-open buffer to avoid latency buildup.
      if (audioBuffer.length > 8) audioBuffer.shift();
    }
  });

  client.on('close', () => {
    console.log(`[STT] Client disconnected: ${email}`);
    clearInterval(keepAlive);
    try { dg.requestClose(); } catch (_) {}
    try { dg.finish(); } catch (_) {}
  });
});

server.listen(PORT, () => console.log(`[Backend] Running on http://localhost:${PORT}`));
