require('dotenv').config();

const fs = require('fs');
const path = require('path');
const http = require('http');
const express = require('express');
const cors = require('cors');
const WebSocket = require('ws');
const { createClient, LiveTranscriptionEvents } = require('@deepgram/sdk');

const PORT = Number(process.env.PORT || 8080);
const DEEPGRAM_API_KEY = process.env.DEEPGRAM_API_KEY;

const DG_MODEL = process.env.DG_MODEL || 'nova-3';
const DG_LANGUAGE = process.env.DG_LANGUAGE || 'en-US';
const DG_ENDPOINTING_MS = Number(process.env.DG_ENDPOINTING_MS || 250);

const USERS_FILE = path.join(__dirname, 'users.json');

function loadUsers() {
  try {
    return JSON.parse(fs.readFileSync(USERS_FILE, 'utf8'));
  } catch {
    return {};
  }
}

function validateLicense(email, licenseKey) {
  const users = loadUsers();
  const cleanEmail = String(email || '').trim().toLowerCase();
  const cleanKey = String(licenseKey || '').trim();

  const user = users[cleanEmail];

  if (!user) return { ok: false, reason: 'License email not found' };
  if (!user.active) return { ok: false, reason: 'License inactive' };
  if (user.licenseKey !== cleanKey) return { ok: false, reason: 'Invalid license key' };

  const today = new Date().toISOString().slice(0, 10);
  if (user.validTill < today) return { ok: false, reason: `License expired on ${user.validTill}` };

  return { ok: true, user };
}

const app = express();
app.use(cors());
app.use(express.json({ limit: '1mb' }));

app.get('/health', (_, res) => {
  res.json({
    ok: true,
    service: 'zupzup-backend',
    model: DG_MODEL,
    language: DG_LANGUAGE,
    endpointing: DG_ENDPOINTING_MS
  });
});

app.post('/api/license/check', (req, res) => {
  const result = validateLicense(req.body.email, req.body.licenseKey);

  res.status(result.ok ? 200 : 403).json(
    result.ok
      ? {
          ok: true,
          validTill: result.user.validTill,
          plan: result.user.plan
        }
      : {
          ok: false,
          error: result.reason
        }
  );
});

app.post('/api/razorpay/webhook', (req, res) => {
  res.json({
    ok: true,
    message: 'Webhook received. Manual license update is enabled.'
  });
});

const server = http.createServer(app);
const wss = new WebSocket.Server({ server, path: '/stt' });

wss.on('connection', (client, req) => {
  const url = new URL(req.url, `http://${req.headers.host}`);

  const email = url.searchParams.get('email');
  const licenseKey = url.searchParams.get('licenseKey');

  const license = validateLicense(email, licenseKey);

  if (!license.ok) {
    const reason =
      license.reason +
      '. Open License in the overlay and activate with the same email/license generated by backend.';

    client.send(JSON.stringify({ type: 'error', message: reason }));
    client.close(4001, reason);
    return;
  }

  if (!DEEPGRAM_API_KEY) {
    client.send(JSON.stringify({
      type: 'error',
      message: 'Backend Deepgram key is not configured'
    }));
    client.close(4002, 'Deepgram key missing');
    return;
  }

  console.log(`[STT] Client connected: ${email}`);

  client.send(JSON.stringify({
    type: 'status',
    text: `License valid. Starting transcription with ${DG_MODEL}...`
  }));

  const deepgram = createClient(DEEPGRAM_API_KEY);

  const dg = deepgram.listen.live({
    model: DG_MODEL,
    language: DG_LANGUAGE,
    encoding: 'linear16',
    sample_rate: 16000,
    channels: 1,

    interim_results: true,
    endpointing: DG_ENDPOINTING_MS,
    vad_events: true,

    punctuate: true,
    smart_format: true,
    filler_words: true,
    profanity_filter: false
  });

  let dgReady = false;
  const audioBuffer = [];

  const keepAlive = setInterval(() => {
    try {
      dg?.keepAlive?.();
    } catch (_) {}
  }, 8000);

  dg.on(LiveTranscriptionEvents.Open, () => {
    dgReady = true;

    client.send(JSON.stringify({
      type: 'status',
      text: `Deepgram connected (${DG_MODEL}). Listening...`
    }));

    for (const chunk of audioBuffer.splice(0)) {
      try {
        dg.send(chunk);
      } catch (_) {}
    }
  });

  dg.on(LiveTranscriptionEvents.Transcript, (data) => {
    const alt = data?.channel?.alternatives?.[0];
    const text = (alt?.transcript || '').trim();

    if (!text) return;

    // Do NOT log transcript text on server.
    client.send(JSON.stringify({
      type: 'transcript',
      text,
      isFinal: !!data?.is_final,
      confidence: alt?.confidence || 0
    }));
  });

  dg.on(LiveTranscriptionEvents.SpeechStarted, () => {
    client.send(JSON.stringify({ type: 'speech_started' }));
  });

  dg.on(LiveTranscriptionEvents.Error, (err) => {
    const message = err?.message || String(err);

    console.error('[Deepgram] Error:', message);

    client.send(JSON.stringify({
      type: 'error',
      message
    }));
  });

  dg.on(LiveTranscriptionEvents.Close, () => {
    dgReady = false;
    clearInterval(keepAlive);
  });

  client.on('message', (chunk) => {
    const buf = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);

    if (dgReady) {
      try {
        dg.send(buf);
      } catch (e) {
        console.error('[STT] send error:', e.message);
      }
    } else {
      audioBuffer.push(buf);

      if (audioBuffer.length > 25) {
        audioBuffer.shift();
      }
    }
  });

  client.on('close', () => {
    console.log(`[STT] Client disconnected: ${email}`);

    clearInterval(keepAlive);

    try {
      dg.requestClose();
    } catch (_) {}

    try {
      dg.finish();
    } catch (_) {}
  });
});

server.listen(PORT, () => {
  console.log(`[Backend] ZupZup backend running on port ${PORT}`);
});